# Base stage for both dev and prod
FROM node:14-alpine as base

RUN mkdir /app/
WORKDIR /app/

RUN apk add --update --no-cache git make python3 g++

COPY package.json /app/
COPY package-lock.json* /app/

RUN npm set progress=true && npm config set depth 0
RUN npm install --package-lock-only --legacy-peer-deps
RUN npm install

COPY . /app/

EXPOSE 3000

CMD ["npm", "run", "dev"]